# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20170210_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
