# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20170210_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='meal',
            field=models.ManyToManyField(blank=True, to='ads.Meal'),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='meal',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
